### ISSUE TITLE
accidental GPL headers

### ISSUE THREAD

**Issue by babbush** [ProjectQ-Framework/FermiLib-Plugin-Psi4#16]
It seems that we have accidentally included the GPL (as opposed to L-GPL) headers in some of the files in this repository. We should fix this. Since this might be construed as changing the license, we need explicitly permission from all contributors:
@jarrodmcc 
@damiansteiger 
@thomashaener 
@idk3 

Does everybody approve? Please just say "yes" if you do. Thanks.

**Comment by damiansteiger** [comment]
Yes, some files are released under a GPL license. I can understand your point of having everything released under a L-GPL license. As you said, a license change requires the necessary permissions. Your list of contributors needs to be extended by all the people mentioned in the first commit message:
> Submitted on behalf of Jarrod McClean (LBNL), Ryan Babbush (Google), Damian Steiger (ETH, Google), Ian Kivlichan (Harvard University), Thomas Häner (ETH), Vojtech Havlicek, Matthew Neeley (Google), and Wei Sun (Google)

Luckily ETH has a CLA from every contributor which gives the permission to release their code under a different license. So we will go ahead and make the change on behalf of ETH.
